# Generated by Django 5.0.4 on 2024-04-18 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id_etudiant', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('cni', models.CharField(max_length=255)),
                ('massar', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('filiere', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id_exemplaire', models.IntegerField(primary_key=True, serialize=False)),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('hors-pret', 'Hors-pret'), ('a_enlever', 'A enlever')], max_length=20)),
                ('date_achat', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id_livre', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('auteur', models.CharField(max_length=255)),
                ('langue', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='./static/boock')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id_emprunt', models.AutoField(primary_key=True, serialize=False)),
                ('date_emprunt', models.DateField()),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effectif', models.DateField()),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='BiblioAPP.etudiant')),
                ('id_exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='BiblioAPP.exemplaire')),
            ],
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='id_livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='BiblioAPP.livre'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('date_reservation', models.DateField()),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='BiblioAPP.etudiant')),
                ('id_livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='BiblioAPP.livre')),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id_sanction', models.IntegerField(primary_key=True, serialize=False)),
                ('type_sanction', models.CharField(choices=[('retard', 'Retard'), ('perte', 'Perte')], max_length=10)),
                ('date_sanction', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='BiblioAPP.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Livre_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioAPP.livre')),
                ('id_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioAPP.reservation')),
            ],
            options={
                'unique_together': {('id_livre', 'id_reservation')},
            },
        ),
    ]
