# Generated by Django 5.0.4 on 2024-04-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioAPP', '0002_etudiant_remove_emprunt_iduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateField(default='1900-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour_effectif',
            field=models.DateField(default='1900-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour_prevue',
            field=models.DateField(default='1900-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(default='1900-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateField(default='2024-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='date_sanction',
            field=models.DateField(default='1900-01-01', null=True),
        ),
    ]
