# Generated by Django 5.0.4 on 2024-04-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioAPP', '0004_alter_emprunt_date_emprunt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='image',
            field=models.ImageField(upload_to='./static/boock'),
        ),
    ]
