# Generated by Django 5.0.4 on 2024-04-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioAPP', '0005_alter_livre_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emprunt',
        ),
    ]
